language: cpp
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get install -qq libboost-dev libboost-system-dev libboost-test-dev libboost-filesystem-dev libboost-thread-dev libssl-dev
  - mkdir build
  - cd build
  - cmake ..

script: make
